# Generated by Django 3.1.7 on 2021-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('description1', models.TextField(blank=True, max_length=1000, null=True)),
                ('description2', models.TextField(blank=True, max_length=1000, null=True)),
                ('live_site', models.URLField()),
                ('github', models.URLField()),
                ('description_image', models.ImageField(upload_to='')),
                ('description_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('description_image2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
