# Generated by Django 3.2.3 on 2021-07-14 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_image',
            new_name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_image2',
        ),
        migrations.AddField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
