# Generated by Django 3.1.7 on 2021-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='that is the title tag', max_length=256),
            preserve_default=False,
        ),
    ]
